# Generated by Django 3.2.4 on 2021-06-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCF', '0002_alter_subscriptions_subscriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='subscriptions',
            new_name='subscription',
        ),
    ]
